import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidenav } from "@/components/ui/sidenav";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="p-4 text-lg border-b-2 flex justify-between">
          <Link href="/">
            <h1>PhotoHub</h1>
          </Link>
          <Avatar>
            <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
        </div>
        <div className=" min-h-screen text-white flex ">
          <div className="w-1/4">
          <Sidenav />
          </div>
          <div className="w-3/4 min-h-screen py-5 px-3 lg:pr-32">{children}</div>
        </div>
      </body>
    </html>
  );
}
