import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidenav } from "@/components/ui/sidenav";
import Link from "next/link";
import Logo from "../../public/icons8-image-gallery-64.png"
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PhotoHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="p-4 text-lg border-b-2 flex justify-between">
          
          <Link  href="/"className="flex ">
            <Image src={Logo} alt="logo"className="w-8 h-7 mr-3" ></Image>
            <h1 className="lg:text-xl">Photo</h1><h1 className="  bg-orange-500 h-[1.7rem] w-10 lg:text-xl text-black font-semibold">Hub</h1>
          </Link>
          
          
          <Avatar>
            <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
        </div>
        <div className=" min-h-screen text-white flex flex-col lg:flex-row">
          <div className="lg:w-1/4 w-full ">
          <Sidenav />
          </div>
          <div className="lg:w-3/4 min-h-screen py-16 lg:py-24 px-3 lg:pr-32">{children}</div>
        </div>
      </body>
    </html>
  );
}
